include:
  - docker-compose.bootstrap.yml

services:  
  blueskyfeed-jetstream:
    image: blueskyfeed.jetstream
    build:
      context: .
      dockerfile: BlueskyFeed/BlueskyFeed.Jetstream/Dockerfile
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__redis: "redis:6379"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_SERVICE_NAME: "BlueskyFeed.Jetstream"
    depends_on:
      - redis
    restart: unless-stopped

  blueskyfeed-api:
    image: blueskyfeed.api
    build:
      context: .
      dockerfile: BlueskyFeed/BlueskyFeed.Api/Dockerfile
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__redis: "redis:6379"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_SERVICE_NAME: "BlueskyFeed.Api"
    ports:
      - "18080:8080"
      - "18443:8443"
      - "5275:8080"
    depends_on:
      - redis
    restart: unless-stopped
