{
 "title": "Jetstream",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Create events/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(collection) (rate(events{job=\"BlueskyFeed.Jetstream\", operation=\"Create\"}[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete events/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(collection) (rate(events{job=\"BlueskyFeed.Jetstream\", operation=\"Delete\"}[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update events/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(collection) (rate(events{job=\"BlueskyFeed.Jetstream\", operation=\"Update\"}[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}